### ISSUE TITLE
When using the package I get an evaporate error

### ISSUE THREAD

**Issue by pglockwo** [kpantic/react-s3-uploader-multipart#1]
**my client code looks like this**
**"http://localhost:3001/s3/sign" this url implements the s3 router that comes out of the package**
        <ReactS3Uploader
              signingUrl="http://localhost:3001/s3/sign"
              signingUrlMethod="GET"
          accept="image/*"
          s3path="/uploads/"
          // preprocess={this.onUploadStart}
          // onProgress={this.onUploadProgress}
          // onError={this.onUploadError}
          // onFinish={this.onUploadFinish}
          // signingUrlHeaders={{ additional: headers }}
          // signingUrlQueryParams={{ additional: query - params }}
          // signingUrlWithCredentials={true}      // in case when need to pass authentication credentials via CORS
          uploadRequestHeaders={{ 'x-amz-acl': 'public-read' }} // this is the default
          contentDisposition="auto"
          // scrubFilename={(filename) => filename.replace(/[^\w\d_\-.]+/ig, '')}
          server="http://localhost:3000"
          //  inputRef={cmp => this.uploadInput = cmp}
          autoUpload={true}
        />

**The error I get is this**

Uncaught TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at S3Upload../node_modules/react-s3-uploader-multipart/s3upload.js.S3Upload.uploadToS3 (s3upload.js:62)
    at S3Upload../node_modules/react-s3-uploader-multipart/s3upload.js.S3Upload.uploadFile (s3upload.js:96)
    at S3Upload.<anonymous> (s3upload.js:55)
    at S3Upload.preprocess (ReactS3Uploader.js:43)
    at S3Upload../node_modules/react-s3-uploader-multipart/s3upload.js.S3Upload.handleFileSelect (s3upload.js:53)
    at new S3Upload (s3upload.js:46)
    at Object.uploadFile (ReactS3Uploader.js:65)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at Object.invokeGuardedCallback (react-dom.development.js:187)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:201)
    at executeDispatch (react-dom.development.js:461)
    at executeDispatchesInOrder (react-dom.development.js:483)
    at executeDispatchesAndRelease (react-dom.development.js:581)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:592)
    at forEachAccumulated (react-dom.development.js:562)
    at runEventsInBatch (react-dom.development.js:723)
    at runExtractedEventsInBatch (react-dom.development.js:732)
    at handleTopLevel (react-dom.development.js:4477)
    at batchedUpdates$1 (react-dom.development.js:16660)
    at batchedUpdates (react-dom.development.js:2131)
    at dispatchEvent (react-dom.development.js:4556)

**Comment by kpantic** [comment]
Hi @pglockwo, you're missing the evaporateOptions property which is reasonable since I didn't update the documentation when updating the library 🤦‍♂️ . I'll update the docs but so you know how to solve your issue, your initialization should look like this:
```
const evaporateOptions = {
   aws_key: AWS_KEY,
   awsRegion: AWS_REGION,
   bucket: AWS_BUCKET,
   awsSignatureVersion: '2',  // This field depends on how you're generating the signature in your backend
   maxConcurrentParts: 10 // You can personalize this to your needs, this is just an example
};

<ReactS3Uploader
evaporateOptions={ evaporateOptions }
signingUrl="http://localhost:3001/s3/sign"
signingUrlMethod="GET"
accept="image/*"
s3path="/uploads/"
uploadRequestHeaders={{ 'x-amz-acl': 'public-read' }} // this is the default
contentDisposition="auto"
server="http://localhost:3000"
autoUpload={true}
/>

```
The AWS_* values need to match what you're uploading the file to, those are just example constants.

**Comment by pglockwo** [comment]
Thank you @kpantic  for that, I have implemented that and now get this error plus the original one

index.js:2178 Warning: React does not recognize the `evaporateOptions` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `evaporateoptions` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input
    in Unknown (created by SampleMediaRequests)
    in div (created by SampleMediaRequests)
    in SampleMediaRequests (created by Connect(SampleMediaRequests))
    in Connect(SampleMediaRequests) (created by Route)
    in Route (created by Routes)
    in div (created by Routes)
    in Routes (created by App)
    in div (created by App)
    in div (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in IntlProvider
    in Provider

**Comment by kpantic** [comment]
Hey @pglockwo, I made a typo in that example, it's not `evaporateOptions`, it's `evaporatorOptions`, sorry about that.

**Comment by pglockwo** [comment]
Hi @kpantic , I get the original error again, I'm not sure the prop evaporatorOptions is passed to the instance of the uploader. In the code it does 

var evaporateOptions = Object.assign(this.evaporateOptions, {
        signerUrl: this.signingUrl
    });

this.evaporateOptions is null always.

**Comment by kpantic** [comment]
Hi @pglockwo, you are completely right, not sure how that was working before. I'm no longer actively using the library so it's a bit hard for me to debug. I published a new version 4.8.1 which should solve the problem if you use the `evaporateOptions` property.

**Comment by hip1310** [comment]
Hi @kpantic , I can't get version 4.8.1 from npm or yarn, looks like it is not published yet and still getting the same error for he evaporateOptions property.

**Comment by billythedummy** [comment]
Hi @kpantic, same here

**Comment by billythedummy** [comment]
I see that it's been fixed on the master branch. Could you please update the package version on npm? Thank you.

**Comment by kpantic** [comment]
@billythedummy The new version has been published!
